### ISSUE TITLE
Node birth messages may not be retained

### ISSUE THREAD

**Issue by pietercardoen** [javier-fg/mqtt-spb-wrapper#3]
Dear

When using your library, I noticed that node birth messages have retained flag set. This is not desirable and in conflict with the sparkplug specification.

The behaviour on edge node disconnect is also not as expected. If an edge node disconnects, the broker must drop the LWT. The edge node doesn't send a DEATH message before disconnecting, then the primary app/other app nodes will never receive the DEATH certificate. Solution for this is to enforce a death message before disconnect.

Kind regards
Pieter Cardoen

**Comment by javier-fg** [comment]
It is intended that on next major release, the birth message will disable the retain flag by default.
For compatibility, It will be left active for the time being

**Comment by javier-fg** [comment]
Latest commit incorporate the publishing of DEATH message upon calling the disconnect function ( it can be also disabled via function parameters).
This change will be pushed on next library update.

**Comment by javier-fg** [comment]
On next library release ( ver 2.0.1 ), this is fixed and an optional parameter is added to set to true the retain flag ( if required), by default is set to false.
