### ISSUE TITLE
Misspelling of "attributes"

### ISSUE THREAD

**Issue by joshwheeler-ggrx** [javier-fg/mqtt-spb-wrapper#4]
I'm assuming that "attribures" is supposed to be "attributes". Can @javier-fg confirm? If so, I can submit a PR. 

https://github.com/javier-fg/mqtt-spb-wrapper/blob/aa935970020831ace0da533dc9052b5346a60bb1/src/mqtt_spb_wrapper/mqtt_spb_wrapper.py#L163

**Comment by javier-fg** [comment]
Last commit to main branch incorporates the fix, soon it will be released in the new version.
