### ISSUE TITLE
Error for connection using SSL 

### ISSUE THREAD

**Issue by juandiz** [javier-fg/mqtt-spb-wrapper#5]
In line 428 of the file mqtt_spb_wrapper.py there is an error in the verification of certificates. The tls_cert_path is used as if it were the tls_ca_path. On the other hand, to correctly start the paho client the function tls_insecure_set() must be called. In case the ssl is enabled tls_insecure_set(True) otherwise tls_insecure_set(False)

**Comment by juandiz** [comment]
````

**Comment by javier-fg** [comment]
Thank you for the fix.
Latest commit incorporates your comments. Also there is a new function parameter "tls_insecure" to disable/enable TLS verification ( for testing purposes / self-signed certificates ).
These changes will be incorporated in the next library revision update.
