### ISSUE TITLE
Update protobuf dependency

### ISSUE THREAD

**Issue by hldiniz** [javier-fg/mqtt-spb-wrapper#8]
Currently the package depends on protobuf==3.20.1
Hoping this dependency can be update to newer version that complies with  protobuf!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<5.0.0dev,>=3.20.3.

**Comment by javier-fg** [comment]
Latest commit incorporates the newer version 3.20.3. I will consider updating it to version 5 on next major release.
Next library update revision will incorporate protobuf version 3.20.3
